--- #YAML:1.0
name:                Task-Compress-Zlib
version:             0.01
abstract:            Installs everything needed for Compress::Zlib
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Algorithm::Dependency:         0
    Class::Autouse:                0
    Class::Inner:                  0
    Class::Inspector:              0
    Compress::Raw::Zlib:           0
    Compress::Zlib:                0
    Config::Tiny:                  0
    Cwd:                           0
    Devel::Symdump:                0
    Error:                         0
    File::Find::Rule:              0
    File::Flat:                    0
    File::Slurp:                   0
    File::Spec:                    0
    Getopt::Long:                  0
    IO:                            0
    IO::Compress::Base:            0
    IO::Compress::Base::Common:    0
    IO::Compress::Gzip:            0
    IO::Compress::Gzip::Constants: 0
    IO::Handle:                    0
    IO::Uncompress::Base:          0
    IO::Uncompress::Gunzip:        0
    IO::Zlib:                      0
    List::Util:                    0
    Params::Util:                  0
    Pod::Escapes:                  0
    Pod::Man:                      0
    Pod::Tests:                    0
    Pod::Usage:                    0
    Scalar::Util:                  0
    Test::ClassAPI:                0
    Test::Harness:                 0
    Test::Inline:                  0
    Test::More:                    0
    Test::Simple:                  0
    Text::Unidecode:               0
    Text::Wrap:                    0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kevin W. Henwood <Khen1950fx@aol.com>
